development:
  adapter: mysql2
  host: localhost
  database: whiteboard_development
  template: template0
  username: root

test:
  adapter: mysql2
  host: localhost
  database: whiteboard_test
  template: template0
  username: root
