---
applications:
- name: whiteboard
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  path: ../../
  host: account-standups-temp
  routes:
    - route: account-standups-temp.cfapps.io
  buildpacks:
    - ruby_buildpack
  stack: cflinuxfs3
