---
applications:
- name: whiteboard
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  path: ../../
  host: whiteboard-production-temp
  buildpack: https://github.com/cloudfoundry/ruby-buildpack#v1.7.17
