---
applications:
- name: whiteboard
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  path: ../../
  routes:
    - route: whiteboard-staging-temp.cfapps.io
  buildpacks:
    - ruby_buildpack
  stack: cflinuxfs3

