---
applications:
- name: whiteboard
  command: bundle exec rake db:migrate && bundle exec unicorn -p $PORT -c ./config/unicorn.rb
  path: ../../
  routes:
    - route: whiteboard-staging-temp.cfapps.io
  buildpacks:
    - https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.40
  stack: cflinuxfs3

