platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: jdk

inputs:
  - name: whiteboard
  - name: acceptance-tests

run:
  path: ./whiteboard/concourse/tasks/acceptance/acceptance.sh